development:
  adapter: mysql2
  database: precis_development
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: precis_test
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: precis_production
  pool: 5
  timeout: 5000
